<?php

namespace Container2enNtG3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_OCK4cEWService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.oCK4cEW' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.oCK4cEW'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'id' => ['privates', '.errored..service_locator.oCK4cEW.App\\Entity\\Task', NULL, 'Cannot autowire service ".service_locator.oCK4cEW": it references class "App\\Entity\\Task" but no such service exists.'],
        ], [
            'id' => 'App\\Entity\\Task',
        ]);
    }
}
