<?php

namespace Container2enNtG3;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTaskService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.oCK4cEW.App\Entity\Task' shared service.
     *
     * @return \App\Entity\Task
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->throw('Cannot autowire service ".service_locator.oCK4cEW": it references class "App\\Entity\\Task" but no such service exists.');
    }
}
