<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'home' => [[], ['_controller' => 'App\\Controller\\TodoController::index'], [], [['text', '/']], [], []],
    'all' => [[], ['_controller' => 'App\\Controller\\TodoController::all'], [], [['text', '/all']], [], []],
    'create-task' => [[], ['_controller' => 'App\\Controller\\TodoController::create'], [], [['text', '/create']], [], []],
    'update-status' => [['id'], ['_controller' => 'App\\Controller\\TodoController::updateTaskStatus'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/updateStatus']], [], []],
    'delete-task' => [['id'], ['_controller' => 'App\\Controller\\TodoController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/deleteTask']], [], []],
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
];
